services:
  adminstack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adminstack
    environment:
      ANSIBLE_CONFIG: /home/ansible/workplace/ansible.cfg
    hostname: adminstack
    image: omniopenverse/adminstack:local
    networks:
      adminstack: null
    ports:
      - 5022:22
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./..
        target: /home/ansible/workplace
        read_only: false
    working_dir: /home/ansible
networks:
  adminstack:
    driver: bridge