services:
  adminstack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adminstack
    environment:
      START_SSH_SERVER: true
      START_VSCODE_SERVER: true
      START_JUPYTER_SERVER: true
      VSCODE_SERVER_PASSWORD: password
    hostname: adminstack
    image: omniopenverse/adminstack:local
    networks:
      adminstack: null
    ports:
      - "${UNIVERSE_HOST:-127.0.0.1}:5022:22"
      - "${UNIVERSE_HOST:-127.0.0.1}:5024:8080"
      - "${UNIVERSE_HOST:-127.0.0.1}:5026:8888"
    restart: unless-stopped
    working_dir: /home/adminstack

networks:
  adminstack:
    driver: bridge
