services:
  adminstack:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adminstack
    environment:
      START_SSHD: true
      START_CODE_SERVER: true
      START_JUPYTER_SERVER: true
      PASSWORD: password # Default password for code-server
    hostname: adminstack
    image: omniopenverse/adminstack:local
    networks:
      adminstack: null
    ports:
      - "${UNIVERSE_HOST:-127.0.0.1}:5022:22"
      - "${UNIVERSE_HOST:-127.0.0.1}:5024:8080"
      - "${UNIVERSE_HOST:-127.0.0.1}:5026:8888"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./..
        target: /home/adminstack/workplace
        read_only: false
      - type: volume
        source: adminstack_ssh
        target: /home/adminstack/.ssh
        volume: {}
    working_dir: /home/adminstack

networks:
  adminstack:
    driver: bridge

volumes:
  adminstack_ssh:
    driver: local