services:
  adminstack:
    volumes:
      - type: bind
        source: ./..
        target: /home/adminstack/workplace
        read_only: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: false
    working_dir: /home/adminstack