services:
  adminstack:
    volumes:
      - type: bind
        source: ./..
        target: /home/adminstack/shared
        read_only: false
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
        bind:
          create_host_path: false
      - type: volume
        source: adminstack_data
        target: /home/adminstack
        volume: {}

volumes:
  adminstack_data:
    driver: local